sudo: required

services:
    - docker

before_install:
    - docker build -t mandlaanilbabu1/loginapp .

script:
    - docker run mandlaanilbabu1/loginapp npm test

after_success:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

    - docker push mandlaanilbabu1/loginapp

deploy:
    provider: elasticbeanstalk
    region: us-east-2
    app: docker-loginapp
    env: DockerLoginapp-env-1
    bucket_name: elasticbeanstalk-us-east-2-840657453070
    bucket_path: docker-loginapp
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_acces_key: $AWS_SECRET_KEY
